from supabase import create_client

SUPABASE_URL = "https://nhfwvxhrfqtygrwpnnhw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZnd2eGhyZnF0eWdyd3Bubmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1NDkyNTYsImV4cCI6MjA5MjEyNTI1Nn0.8QL-ZXM6HjxjwAR_h3PMR1qbXQqvv72T1bBx86ryKKc"

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)